skillMetadata:
   sections:
      - name: Custom url 1
        fields:
          - name: name_1
            type: text
            label: The spoken name of the website
            value:
          - name: url_1
            type: text
            label: The custom url
            value:
      - name: Custom url 2
        fields:
          - name: name_2
            type: text
            label: The spoken name of the website
            value:
          - name: url_2
            type: text
            label: The custom url
            value:
      - name: Custom url 3
        fields:
          - name: name_3
            type: text
            label: The spoken name of the website
            value:
          - name: url_3
            type: text
            label: The custom url
            value:
      - name: Custom url 4
        fields:
          - name: name_4
            type: text
            label: The spoken name of the website
            value:
          - name: url_4
            type: text
            label: The custom url
            value:
      - name: Custom url 5
        fields:
          - name: name_5
            type: text
            label: The spoken name of the website
            value:
          - name: url_5
            type: text
            label: The custom url
            value: