skillMetadata:
   sections:
      - name: Custom url 1
        fields:
          - name: name_one
            type: text
            label: The spoken name of the website
            value:
          - name: url_one
            type: text
            label: The custom url
            value:
      - name: Custom url 2
        fields:
          - name: name_two
            type: text
            label: The spoken name of the website
            value:
          - name: url_two
            type: text
            label: The custom url
            value:
      - name: Custom url 3
        fields:
          - name: name_three
            type: text
            label: The spoken name of the website
            value:
          - name: url_three
            type: text
            label: The custom url
            value: